const TYPES = {
  // MAIN TYPES FOR CONTROLLERS
  CREDIT: 'CREDIT',
  NORMAL: 'NORMAL',
  POSTS: 'POSTS',

  // CONVENTION
  // ACTION CATEGORY/ACTION_NAME
  CREDIT_COUNT: 'CREDIT/COUNTER',
  NORMAL_COUNT: 'NORMAL/COUNTER',
  FETCH_POSTS: 'POSTS/FETCH_POSTS',
};

export default TYPES;
